; Puente ESP-NOW
; Recibe la telemetría del nodo por ESP-NOW y la reenvía por USB-CDC a la 
; estación base.
; La consola de depuración y el enlace con la base comparten el USB-CDC (Serial).

[env:esp32-c3-supermini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework = arduino
monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
