; Configuración del nodo solar autónomo (práctica Sistemas Digitales)
; La consola de depuración sale por USB-CDC (Serial) y el enlace con la
; estación base viaja por el UART0 físico (Serial1, GPIO21/GPIO20).

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
framework = arduino
monitor_speed = 115200

; Habilitar la consola USB-CDC dejando el UART0 libre para la estación base
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Librerías de sensores y comunicación
lib_deps =
    adafruit/Adafruit AHTX0
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit VEML7700 Library
    robtillaart/INA226
    sparkfun/SparkFun AS3935 Lightning Detector Arduino Library
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    bblanchon/ArduinoJson
    marvinroger/AsyncMqttClient