; Estación auxiliar (Cheap Yellow Display 2432S028R).
; Broker sin TLS en la misma LAN

[env:cyd]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=1
    -D USE_HSPI_PORT
    -D LOAD_GLCD
    -D SPI_FREQUENCY=40000000
    -D TFT_INVERSION_ON

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson@^7
    marvinroger/AsyncMqttClient
